import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { NavigationProvider } from "@/context/NavigationContext";
import { NavigationMenu } from "@/components/ui/NavigationMenu";
import { ScaleWrapper } from "@/components/ui/ScaleWrapper";
import { GlobalZoom } from "@/components/ui/GlobalZoom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebas = Bebas_Neue({
  weight: "400",
  variable: "--font-bebas",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebas.variable} antialiased bg-white`}>
        <GlobalZoom />
        <NavigationProvider>
          <NavigationMenu />
          <ScaleWrapper>
            {children}
          </ScaleWrapper>
        </NavigationProvider>
      </body>
    </html>
  );
}
